Updating Rows & Columns

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('results.csv')
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [4]:
df.rename(columns={'ConvertedCompYearly':'SalaryUSD'}, inplace=True)
df

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,SalaryUSD,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65432,65433,I am a developer by profession,18-24 years old,"Employed, full-time",Remote,Apples,Hobby;School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","On the job training;School (i.e., University, ...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65433,65434,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65434,65435,I am a developer by profession,25-34 years old,"Employed, full-time",In-person,Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Social ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65435,65436,I am a developer by profession,18-24 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,"Secondary school (e.g. American high school, G...",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
65436,65437,I code primarily as a hobby,18-24 years old,"Student, full-time",NaN,Apples,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
print("\nchecking whether it is done or not:")
df['SalaryUSD']

checking whether it is done or not:

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
65432   NaN
65433   NaN
65434   NaN
65435   NaN
65436   NaN
Name: SalaryUSD, Length: 65437, dtype: float64

In [8]:
df['RemoteWork']=df['RemoteWork'].map({'Remote':'WorkfromHome','In-person':"Office",'Hybrid':'Both'})
df['RemoteWork']

0        WorkfromHome
1        WorkfromHome
2        WorkfromHome
3                 NaN
4                 NaN
             ...
65432    WorkfromHome
65433    WorkfromHome
65434          Office
65435             NaN
65436             NaN
Name: RemoteWork, Length: 65437, dtype: str

In [11]:
df['Check']=df['Check'].astype(str).str.lower()
df['Check']

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
65432    NaN
65433    NaN
65434    NaN
65435    NaN
65436    NaN
Name: Check, Length: 65437, dtype: str

In [20]:
df['CodingActivities'] = df['CodingActivities'].str.replace(';', ',', regex=False)
df['CodingActivities']

0                                                    Hobby
1        Hobby,Contribute to open-source projects,Other...
2        Hobby,Contribute to open-source projects,Other...
3                                                      NaN
4                                                      NaN
                               ...
65432                        Hobby,School or academic work
65433             Hobby,Contribute to open-source projects
65434                                                Hobby
65435    Hobby,Contribute to open-source projects,Profe...
65436                                                  NaN
Name: CodingActivities, Length: 65437, dtype: str

In [21]:
df['Check'] = df['Check'].replace({'Apples': 'Verified'})
df['Check']

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
65432    NaN
65433    NaN
65434    NaN
65435    NaN
65436    NaN
Name: Check, Length: 65437, dtype: str

In [25]:
df_lowercase = df.astype(str).apply(lambda col: col.str.lower())
df_lowercase

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,SalaryUSD,JobSat
0,1,i am a developer by profession,under 18 years old,"employed, full-time",workfromhome,NaN,hobby,primary/elementary school,books / physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,i am a developer by profession,35-44 years old,"employed, full-time",workfromhome,NaN,"hobby,contribute to open-source projects,other...","bachelor’s degree (b.a., b.s., b.eng., etc.)",books / physical media;colleague;on the job tr...,technical documentation;blogs;books;written tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,i am a developer by profession,45-54 years old,"employed, full-time",workfromhome,NaN,"hobby,contribute to open-source projects,other...","master’s degree (m.a., m.s., m.eng., mba, etc.)",books / physical media;colleague;on the job tr...,technical documentation;blogs;books;written tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,appropriate in length,easy,NaN,NaN
3,4,i am learning to code,18-24 years old,"student, full-time",NaN,NaN,NaN,some college/university study without earning ...,"other online resources (e.g., videos, blogs, f...",stack overflow;how-to videos;interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,too long,easy,NaN,NaN
4,5,i am a developer by profession,18-24 years old,"student, full-time",NaN,NaN,NaN,"secondary school (e.g. american high school, g...","other online resources (e.g., videos, blogs, f...",technical documentation;blogs;written tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,too short,easy,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65432,65433,i am a developer by profession,18-24 years old,"employed, full-time",workfromhome,NaN,"hobby,school or academic work","bachelor’s degree (b.a., b.s., b.eng., etc.)","on the job training;school (i.e., university, ...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65433,65434,i am a developer by profession,25-34 years old,"employed, full-time",workfromhome,NaN,"hobby,contribute to open-source projects",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65434,65435,i am a developer by profession,25-34 years old,"employed, full-time",office,NaN,hobby,"bachelor’s degree (b.a., b.s., b.eng., etc.)","other online resources (e.g., videos, blogs, f...",technical documentation;stack overflow;social ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65435,65436,i am a developer by profession,18-24 years old,"employed, full-time",NaN,NaN,"hobby,contribute to open-source projects,profe...","secondary school (e.g. american high school, g...",on the job training;other online resources (e....,technical documentation;blogs;written tutorial...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
65436,65437,i code primarily as a hobby,18-24 years old,"student, full-time",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
# Only changes "Apples". Every other row stays exactly as it was.
df['Check'] = df['Check'].replace({'Apples': 'Verified'})
df['Check']

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
65432    NaN
65433    NaN
65434    NaN
65435    NaN
65436    NaN
Name: Check, Length: 65437, dtype: str